openapi: 3.0.3
info:
  title: URL Shortner
  description: |-
    FooBar
  contact:
    email: apiteam@swagger.io
  license:
    name: AGPL
    url: https://www.gnu.org/licenses/agpl-3.0.de.html
  version: 1.0.0
paths:
  /api/short:
    post:
      summary: Create a new Short Link
      description: Add a new pet to the store
      operationId: addPet
      requestBody:
        description: Create a new shorten URL
        content:
          application/json:
            schema:
              type: object
              properties:
                target_slug:
                  type: string
                target_url:
                  type: string
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  qrcode:
                    type: string
                  short_url:
                    type: string
                  target_url:
                    type: string
                  target_slug:
                    type: string
        '400':
          description: Invalid input
        '422':
          description: Validation exception
