version: "3.6"


services:
  urlshortner:
    image: urlshortner
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
     - ./urls.yaml:/app/urls.yaml
     - ./src/urlshortener:/app/urlshortener
    environment:
      - URLSHORTNER_SECRET_KEY=cheishue5zoo8chiegiuH5ahtoo$ho
      - URLSHORTNER_URL=https://short.flatos
      - FLASK_DEBUG=true